################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[en.params]
home = "Home"
copyright = "Â© 2025 Christian Guzman. All rights reserved."

# ################################### French language #####################################
# [fr]
# languageName = "Fr"
# languageCode = "fr-fr"
# contentDir = "content/french"
# weight = 2
# [fr.params]
# home = "Accueil"
# copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
